import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

export interface GenerateOptions {
  name: string;
  description?: string;
  dir?: string;
  force?: boolean;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface WriteResult {
  root: string;
  files: string[];
}

export function normalizeSkillName(input: string): string {
  const normalized = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");

  if (!normalized) {
    throw new Error("Skill name must contain at least one letter or number.");
  }

  return normalized;
}

export function createSkillFiles(options: GenerateOptions): GeneratedFile[] {
  const name = normalizeSkillName(options.name);
  const title = toTitle(name);
  const description =
    options.description ??
    `Use when a user needs a repeatable ${title} workflow for AI coding agents.`;

  return [
    {
      path: "SKILL.md",
      content: createSkillMarkdown(name, title, description),
    },
    {
      path: "README.md",
      content: createReadmeMarkdown(name, title),
    },
    {
      path: path.join("examples", "usage.md"),
      content: createUsageMarkdown(name, title),
    },
  ];
}

export async function writeSkillFolder(options: GenerateOptions): Promise<WriteResult> {
  const name = normalizeSkillName(options.name);
  const parentDir = path.resolve(options.dir ?? process.cwd());
  const root = path.join(parentDir, name);
  const files = createSkillFiles(options);

  await mkdir(root, { recursive: options.force === true });
  await mkdir(path.join(root, "examples"), { recursive: true });

  const written: string[] = [];
  for (const file of files) {
    const target = path.join(root, file.path);
    await writeFile(target, file.content, {
      encoding: "utf8",
      flag: options.force === true ? "w" : "wx",
    });
    written.push(target);
  }

  return { root, files: written };
}

export function createSkillMarkdown(name: string, title = toTitle(name), description?: string): string {
  const frontmatterDescription =
    description ?? `Use when a user needs a repeatable ${title} workflow for AI coding agents.`;

  return `---
name: ${name}
description: "${escapeFrontmatter(frontmatterDescription)}"
---

# ${title}

## When To Use

Use this skill when the user asks for ${title.toLowerCase()} help, wants a repeatable workflow, or needs agent-ready instructions that can be reused across sessions.

## Trigger Phrases

- "${name}"
- "${title}"
- "create a ${title.toLowerCase()} workflow"
- "reuse this ${title.toLowerCase()} process"

## Workflow

1. Clarify the target outcome in one sentence.
2. Inspect the relevant files, links, or examples before changing anything.
3. Draft the smallest useful output first.
4. Validate the result with a concrete command, checklist, or visual review.
5. Report what changed, what was verified, and what remains risky.

## Quality Checklist

- The output is specific to the user's context.
- The workflow avoids hidden network calls and secret handling.
- The final answer includes exact files, commands, or artifacts when relevant.
- The verification step proves the result works.

## Example Prompts

- "Use ${title} to turn this repeated task into a reusable process."
- "Create a ${name} skill for this workflow."
- "Check whether this ${title.toLowerCase()} skill has clear triggers and verification steps."
`;
}

function createReadmeMarkdown(name: string, title: string): string {
  return `# ${title}

Portable AI-agent skill generated by agent-skill-smith.

## Files

- \`SKILL.md\` - agent-facing instructions.
- \`examples/usage.md\` - prompts and expected use cases.

## Install

Copy this folder into your agent skills directory, then restart or reload your coding agent.

## Validate

\`\`\`bash
agent-skill-smith check ${name}
\`\`\`
`;
}

function createUsageMarkdown(name: string, title: string): string {
  return `# ${title} Usage

## Example

\`\`\`text
Use ${title} to create a reusable workflow for my current project.
\`\`\`

## Expected Agent Behavior

The agent should read \`SKILL.md\`, follow the workflow, and verify the result before claiming completion.

## Maintenance

Run this after edits:

\`\`\`bash
agent-skill-smith check ${name}
\`\`\`
`;
}

function toTitle(slug: string): string {
  const acronyms: Record<string, string> = {
    ai: "AI",
    api: "API",
    cli: "CLI",
    css: "CSS",
    html: "HTML",
    json: "JSON",
    llm: "LLM",
    mcp: "MCP",
    pdf: "PDF",
    seo: "SEO",
    sql: "SQL",
    ui: "UI",
    ux: "UX",
    yaml: "YAML",
  };

  return slug
    .split("-")
    .filter(Boolean)
    .map((part) => acronyms[part] ?? part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function escapeFrontmatter(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
